name: Hello World

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout our repository
      uses: actions/checkout@v4

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          git clone git@github.com:Azizbek-Qodirov/web-poll.git
          sudo docker network create global-net

          cd forum-project
          sudo docker compose down
          sudo docker compose up -d
          echo dir changed to forum-project main directory, up and down

          cd ../api-gateway
          sudo docker compose down
          sudo docker compose up -d
          echo dir changed to api-gateway directory, up and down

          cd ../auth-service
          sudo docker compose down
          sudo docker compose up -d
          echo dir changed to auth-service directory, up and down

          cd ../forum-service
          sudo docker compose down 
          sudo docker compose up -d
          echo dir changed to forum-service directory, up and down