
Skip to content
Navigation Menu

    Azizbek-Qodirov
    /
    web-poll

Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights

    Settings

Web Polling Service
done #14

Jobs

Run details

Workflow file for this run
.github/workflows/deploy.yml at 59552a2
name: Web Polling Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Define ANSI color codes
            RED='\033[0;31m'
            GREEN='\033[0;32m'
            YELLOW='\033[1;33m'
            BLUE='\033[0;34m'
            NC='\033[0m' # No Color
            function log_info {
              echo -e "${YELLOW}$1${NC}"
            }
            function log_success {
              echo -e "${GREEN}$1${NC}"
            }
            function log_error {
              echo -e "${RED}$1${NC}"
            }
            # Pull latest code from GitHub
            log_info "---------------- PULLING CODE FROM GITHUB ----------------"
            cd web-poll
            git pull origin main
            log_success "---------------- CODE PULLED FROM GITHUB -----------------"
            # Restart polling service
            log_info "---------------- NAVIGATING TO POLLING DIRECTORY ----------------"
            cd polling
            sudo docker compose down
            log_error "---------------- POLLING SERVICES STOPPED ----------------"
            sudo docker compose up --build -d
            log_success "---------------- POLLING SERVICES STARTED ----------------"
            # Restart API Gateway service
            log_info "---------------- NAVIGATING TO API-GATEWAY DIRECTORY ----------------"
            cd ../api-gateway
            sudo docker compose down
            log_error "---------------- API-GATEWAY SERVICES STOPPED ----------------"
            sudo docker compose up --build -d
            log_success "---------------- API-GATEWAY SERVICES STARTED ----------------"
done Â· Azizbek-Qodirov/web-poll@59552a2

